### ISSUE TITLE
Implement titlecase iterator

### ISSUE THREAD

**Issue by lopopolo** [artichoke/roe#65]
Implement a `Titlecase` iterator similar to the `Lowercase` and `Uppercase` iterators already in this crate.

Unlike `Lowercase` and `Uppercase`, `char::to_titlecase` is not defined in `std`, so we'll have to generate mappings for the titlecase transforms.

One way we might do that is to roll some Ruby scripts like `focaccia` does for generating case folding mappings:

- https://github.com/artichoke/focaccia/blob/ed00eb45e6d1a38dda145cfae2b64c215119a2fe/scripts/gen_case_lookups.rb
- https://github.com/artichoke/focaccia/blob/ed00eb45e6d1a38dda145cfae2b64c215119a2fe/Rakefile#L92-L104

Another way we might tackle this is with codegen from crates in the Rust ecosystem:

- https://crates.io/crates/ucd-generate

Use the source layout of the `Lowercase` iterator as a guide:

- https://github.com/artichoke/roe/blob/acdab1e6b2b1eea475e8eea8a0a7c616ce7bf850/src/lowercase.rs
- https://github.com/artichoke/roe/tree/acdab1e6b2b1eea475e8eea8a0a7c616ce7bf850/src/lowercase
- https://github.com/artichoke/roe/blob/acdab1e6b2b1eea475e8eea8a0a7c616ce7bf850/src/lib.rs#L180-L320

## Implementation steps

- Implement `TitlecaseMode`.
- Implement ASCII iterator.
- Implement Full iterator.
- Wire everything up in a free function entrypoint in `lib.rs`.

**Comment by choznerol** [comment]
I'd like to work on this one if nobody is currently working on it 🤚

**Comment by lopopolo** [comment]
Go for it!
